### ISSUE TITLE
gatekeeper client doesnt work with response wrapping

### ISSUE THREAD

**Issue by Zariel** [ChannelMeter/vault-gatekeeper-mesos#12]
The client in `gatekeeper/` does not work with response wrapping, the permanent token needs to be unmarssalled from the json data in `data.response` from cubbyhole contents.

This is easily doable with https://godoc.org/github.com/hashicorp/vault/api#Logical.Unwrap

**Comment by nemothekid** [comment]
f814066ded9419142f208a1665c8845374b26f60 should have this functionality. I'll take a look at it again.

**Comment by chill** [comment]
Feels like it'd be a good idea to use the vault client across the board when making requests to Vault, as it greatly simplifies a lot of this stuff

**Comment by nemothekid** [comment]
I see the issue actually, you are right it doesn't work.

**Comment by nemothekid** [comment]
Scratch that, I lied.

**Comment by nemothekid** [comment]
I lied about lying, it doesn't work. It isn't unwrapped correctly.
