### ISSUE TITLE
VAULT_TOKEN strategies

### ISSUE THREAD

**Issue by broamski** [ChannelMeter/vault-gatekeeper-mesos#23]
This is less of an issue and more of a discussion, but what are some strategies around managing the lifecycle of the credentials provided to `vault-gatekeeper-mesos`? Using a root token (e.g. the only token which doesn't have an expiration) in `VAULT_TOKEN` isn't very desirable, so I'm eager to hear your thoughts.

**Comment by nemothekid** [comment]
You can create a token, that isn't a root token with the [default policy](https://github.com/ChannelMeter/vault-gatekeeper-mesos/blob/6cda3a058e963208a4f6c883f17e40e5df3116a1/gatekeeper-policy.hcl), and assign with a TTL.

Gatekeeper will automatically [renew the token when it approaches it's TTL](https://github.com/ChannelMeter/vault-gatekeeper-mesos/blob/6cda3a058e963208a4f6c883f17e40e5df3116a1/gatekeeper.go#L164). 

On top of that, tokens typically have maximum TTLs (for example you can set a TTL for 3600 seconds, but you can only renew that token continually for a week). In that case, gatekeeper will try to create a [brand new token with the same permissions as the token it was given](https://github.com/ChannelMeter/vault-gatekeeper-mesos/blob/6cda3a058e963208a4f6c883f17e40e5df3116a1/gatekeeper.go#L116). 

With these settings, in a perfect world, gatekeeper will run indefinitely. However, you should still setup some monitoring (like pinging `/status.json`) to ensure gatekeeper doesn't get sealed. Things like network timeouts can compromise this process.

**Comment by broamski** [comment]
Nice. Thanks. I hadn't had enough time to dig in and find `renew_worker`. Thanks for the details!

**Comment by matkam** [comment]
Would be nice to add some retry logic to the recreate function in case of unexpected errors:
```
2017/06/10 22:28:41 Renewing token with ttl of 768h0m0s.
2017/06/10 22:28:41 Renewed token with ttl of 768h0m0s.
2017/06/10 22:28:41 Failed to lookup token. Error Code: 404
```
