### ISSUE TITLE
Enhancement request: Allow only one request for a token per task ID within startup window

### ISSUE THREAD

**Issue by psfblair** [ChannelMeter/vault-gatekeeper-mesos#30]
As I understand it, the gatekeeper checks to make sure that a request for a token is coming from a process recently started by Mesos. However, this still leaves open a spoofing attack whereby an attacker uses the task ID to make a second token request successfully.

It would be nice to know that a token can only be requested once for a given task ID within the "recently started" time window. Or is this already implemented?

**Comment by nemothekid** [comment]
We maintain an expiring set to keep track of processes we have already given tokens too. This also gives you the ability to detect malicious activity - if you request a token and it was already used, someone may have stolen it (or there is a bug in your code).

https://github.com/ChannelMeter/vault-gatekeeper-mesos/blob/master/provider.go#L138

**Comment by psfblair** [comment]
Thanks! Good to know.
