### ISSUE TITLE
Regularly update image via Repository link to pull in security fixes

### ISSUE THREAD

**Issue by albuch** [ChannelMeter/vault-gatekeeper-mesos#45]
To get all golang and Alpine security fixes in more frequently an automated build could be set up in Docker Hub listening on upstream repository changes via Repository links.
https://docs.docker.com/docker-hub/builds/#repository-links

If corresponding golang image changes the vault-mesos-gatekeeper image could be rebuilt and re-published under the same tag.

Currently the Alpine base image has several critical security issues that have fixes available.

**Comment by albuch** [comment]
Hi @nemosupremo

**Comment by nemosupremo** [comment]
I'm looking into this - there are some organizational changes that may lead me to continue development under a fork. I'm going to look into the outstanding PRs this week as well.
